import threading
import time
import webbrowser
from datetime import datetime

import rumps

# A stable identifier used to look up this plugin's saved configuration
# inside core.settings["plugins"]["config"].
PLUGIN_NAME = "menu_template"


def get_settings_schema():
    """
    Return the plugin settings schema.

    SwitchBored uses this schema to:
    - expose editable settings in the plugin manager
    - provide default values
    - describe each setting in the UI

    Each key becomes one configurable field for this plugin.
    """
    return {
        "enabled": {
            "type": "bool",
            "default": True,
            "label": "Enable Menu Template",
        },
        "interval_s": {
            "type": "int",
            "default": 60,
            "label": "Polling interval (seconds)",
        },
        "menu_title": {
            "type": "str",
            "default": "Template Plugin",
            "label": "Top-level menu title",
        },
        "show_timestamp": {
            "type": "bool",
            "default": True,
            "label": "Show last refresh time",
        },
    }


class Plugin:
    """
    Example SwitchBored plugin demonstrating how to:

    - define editable plugin settings
    - build a submenu in the rumps menu bar UI
    - add clickable and non-clickable menu items
    - run background work on a thread
    - push results into the menu safely using a timer
    - clean up worker state when the plugin stops
    """

    def __init__(self, core):
        """
        Store the shared core object and initialize plugin state.

        The host application passes `core` when loading the plugin.
        This gives the plugin access to:
        - settings
        - logging
        - shared helper methods
        """
        self.core = core
        self.schema = get_settings_schema()

        # The top-level rumps menu item created for this plugin.
        # Example: "Template Plugin" in the menu bar dropdown.
        self.master_menu = None

        # Dictionary of child menu items keyed by a stable internal name.
        # This makes it easy to update titles later without rebuilding the menu.
        self.items = {}

        # Latest data generated by the background worker.
        # The timer reads from this and updates menu item titles.
        self.latest_payload = None

        # Threading primitives for clean start/stop behavior.
        self._stop = threading.Event()
        self._thread = None
        self._timer = None

    # -------------------------------------------------------------------------
    # Settings
    # -------------------------------------------------------------------------

    def _cfg(self):
        """
        Return the effective plugin configuration.

        This merges user-saved settings with schema defaults so the plugin
        always has a complete config dictionary, even if some values have
        never been edited by the user.
        """
        try:
            user_cfg = (
                self.core.settings
                .get("plugins", {})
                .get("config", {})
                .get(PLUGIN_NAME, {})
            )
        except Exception:
            user_cfg = {}

        merged = {}
        for key, spec in self.schema.items():
            merged[key] = user_cfg.get(key, spec.get("default"))
        return merged

    # -------------------------------------------------------------------------
    # Menu helpers
    # -------------------------------------------------------------------------

    def create_item(self, key, title, callback=None, parent=None):
        """
        Create a rumps menu item and store it in self.items.

        Parameters
        ----------
        key:
            Internal identifier used later when updating the item.
        title:
            Text shown in the menu.
        callback:
            Function to call when the menu item is clicked.
            If omitted, the item is displayed as non-interactive.
        parent:
            Optional submenu parent. If omitted, the item is added directly
            under this plugin's top-level menu.
        """
        container = parent or self.master_menu
        if container is None:
            raise RuntimeError("Master menu has not been built yet.")

        item = rumps.MenuItem(title, callback=callback)

        # rumps does not provide a perfect high-level API for "display-only"
        # menu items, so for a no-callback item we explicitly disable it.
        if callback is None:
            item.set_callback(None)
            try:
                item._menuitem.setEnabled_(False)
            except Exception:
                pass

        container.add(item)
        self.items[key] = item
        return item

    def update_item(self, key, new_title):
        """
        Update the visible text of an existing menu item.

        If the item is missing, this method silently does nothing.
        That keeps UI refresh code simple and resilient.
        """
        item = self.items.get(key)
        if item is not None:
            item.title = new_title

    def add_separator(self, parent=None):
        """
        Add a separator line to the menu.

        Separators are useful for visually grouping related menu actions.
        """
        container = parent or self.master_menu
        if container is not None:
            container.add(rumps.separator)

    # -------------------------------------------------------------------------
    # Popup helper
    # -------------------------------------------------------------------------

    def show_popup(self, title="Template Plugin", message="This is a placeholder popup."):
        """
        Show a simple detached popup window.

        This uses a small standalone CustomTkinter process instead of trying
        to embed a complex Tk window directly into the menu bar process.
        That keeps the example simple and avoids blocking the main menu app.

        Note: spawning `sys.executable -c` only works when SwitchBored runs
        from source. Inside a packaged .app, prefer rumps.alert() or
        rumps.notification() for user-facing messages.
        """
        import subprocess
        import sys
        import textwrap

        popup_script = textwrap.dedent(f"""
            import customtkinter as ctk

            app = ctk.CTk()
            app.withdraw()

            app.title({title!r})
            app.resizable(False, False)
            app.attributes("-topmost", True)

            width = 340
            height = 170
            x = (app.winfo_screenwidth() // 2) - (width // 2)
            y = (app.winfo_screenheight() // 2) - (height // 2)
            app.geometry(f"{{width}}x{{height}}+{{x}}+{{y}}")

            frame = ctk.CTkFrame(app, corner_radius=12)
            frame.pack(fill="both", expand=True, padx=16, pady=16)

            ctk.CTkLabel(
                frame,
                text={title!r},
                font=("", 20, "bold")
            ).pack(pady=(12, 6))

            ctk.CTkLabel(
                frame,
                text={message!r},
                justify="center",
                wraplength=280
            ).pack(pady=(0, 14))

            ctk.CTkButton(
                frame,
                text="OK",
                width=90,
                command=app.destroy
            ).pack(pady=(0, 10))

            app.deiconify()
            app.lift()
            app.focus_force()
            app.mainloop()
        """)

        subprocess.Popen([sys.executable, "-c", popup_script])

    # -------------------------------------------------------------------------
    # Menu callbacks
    # -------------------------------------------------------------------------

    def on_refresh_now(self, sender):
        """
        Refresh the plugin data immediately.

        This demonstrates a simple menu action callback.
        The `sender` argument is supplied by rumps when the item is clicked.
        """
        self._fetch_once()

    def on_show_info(self, sender):
        """
        Show an example popup window.

        Useful as a template for plugins that want to display a small
        information or status dialog outside the menu.
        """
        self.show_popup(
            title="Template Plugin",
            message="This is a placeholder popup from the example plugin."
        )

    def on_open_time_search(self, sender):
        """
        Open a browser action from a menu item.

        This is a minimal example of launching an external action from the menu.
        """
        webbrowser.open("https://www.google.com/search?q=local+time")

    # -------------------------------------------------------------------------
    # Plugin lifecycle
    # -------------------------------------------------------------------------

    def on_menu_build(self, app):
        """
        Build this plugin's menu inside the host application's menu.

        The host calls this during menu construction. This is where the plugin:
        - checks whether it is enabled
        - creates its top-level menu
        - adds actions and status items
        - starts background work and UI refresh timers
        """
        cfg = self._cfg()
        if not cfg.get("enabled", True):
            return

        self.core.log("PLUGIN", f"{PLUGIN_NAME}: building menu")

        self.master_menu = rumps.MenuItem(cfg.get("menu_title", "Template Plugin"))
        app.menu.add(self.master_menu)

        # Example clickable status item.
        # Here we make the status line itself clickable just to demonstrate that
        # a "status" row can also act like a shortcut.
        self.create_item(
            key="status",
            title="Status: waiting for first refresh...",
            callback=self.on_open_time_search,
        )

        # Example action that opens a popup window.
        self.create_item(
            key="action_info",
            title="Show example popup",
            callback=self.on_show_info,
        )

        # Example action that forces an immediate refresh.
        self.create_item(
            key="action_refresh",
            title="Refresh now",
            callback=self.on_refresh_now,
        )

        self.add_separator()

        # Example display-only item.
        # Because callback=None, this row is shown as informational only.
        if cfg.get("show_timestamp", True):
            self.create_item(
                key="updated",
                title="Last updated: --",
                callback=None,
            )

        # Start the background worker thread once.
        if not self._thread or not self._thread.is_alive():
            self._stop.clear()
            self._thread = threading.Thread(target=self._fetch_loop, daemon=True)
            self._thread.start()

        # Start the lightweight UI timer once.
        # The timer runs on the rumps side and copies the latest worker output
        # into the visible menu items.
        if not self._timer:
            self._timer = rumps.Timer(self._tick, 1)
            self._timer.start()

    def stop(self):
        """
        Stop the plugin's timer and background thread.

        The host should call this during shutdown or reload so the plugin can
        clean up gracefully.
        """
        self._stop.set()

        if self._timer:
            self._timer.stop()
            self._timer = None

        if self._thread:
            self._thread.join(timeout=1)
            self._thread = None

    # -------------------------------------------------------------------------
    # Background work
    # -------------------------------------------------------------------------

    def build_display_text(self):
        """
        Generate the display text shown in the menu.

        This example shows the local time, but a real plugin might:
        - fetch an API
        - inspect a file
        - query hardware
        - read a database
        """
        now = datetime.now()
        return f"Local time is {now.strftime('%H:%M:%S')}"

    def _fetch_once(self):
        """
        Run one background data refresh.

        This method is called both:
        - by the worker loop on a schedule
        - by the "Refresh now" menu action
        """
        try:
            text = self.build_display_text()
            now = datetime.now().strftime("%H:%M:%S")
            self.latest_payload = {
                "display_text": text,
                "updated_at": now,
            }
        except Exception as e:
            self.latest_payload = {
                "display_text": f"error - {e}",
                "updated_at": "failed",
            }
            self.core.log("PLUGIN", f"{PLUGIN_NAME}: build_display_text failed: {e}")

    def _fetch_loop(self):
        """
        Background polling loop.

        The worker thread does not touch rumps menu items directly.
        Instead, it updates self.latest_payload, and the UI timer reads from that.
        This keeps background work separate from menu updates.
        """
        while not self._stop.is_set():
            self._fetch_once()

            interval = int(self._cfg().get("interval_s", 60))
            for _ in range(interval):
                if self._stop.is_set():
                    return
                time.sleep(1)

    # -------------------------------------------------------------------------
    # UI update loop
    # -------------------------------------------------------------------------

    def _tick(self, sender):
        """
        Copy the latest worker data into the visible menu items.

        This timer callback is the bridge between:
        - background state (`self.latest_payload`)
        - the live rumps UI (`self.items`)
        """
        try:
            if not self.latest_payload:
                return

            payload = self.latest_payload
            display_text = payload.get("display_text", "No data")
            updated_at = payload.get("updated_at", "--")

            self.update_item("status", f"Status: {display_text}")

            if "updated" in self.items:
                self.update_item("updated", f"Last updated: {updated_at}")

        except Exception as e:
            self.core.log("PLUGIN", f"{PLUGIN_NAME}: tick crash: {e}")